name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download zig
        run: wget https://ziglang.org/builds/zig-linux-x86_64-0.12.0-dev.2540+776cd673f.tar.xz

      - name: Extract 
        run: tar -xf zig-linux-x86_64-0.12.0-dev.2540+776cd673f.tar.xz -C zig-0.12.0

      - name: Alias
        run: alias zig='$PWD/zig-0.12.0/zig'

      - name: Version
        run: zig version
        
      - name: Test
        run: zig build test